/**
 * FoodKnock Quick Order — Data File
 * All shop definitions and menu items live here.
 * Edit this file to add/remove shops or menu items.
 * 
 */

const SHOPS = [
  {
    id: "sanwariya-bakers",
    name: "Sanwariya Bakers",
    tagline: "Fresh Baked, Daily Made",
    emoji: "🥐",
    accent: "#f97316",
    gradient: "linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)",
    accentLight: "rgba(249,115,22,0.10)",
    whatsapp: "919876543210",
    category: "Bakery & Snacks",
    menu: [
      { id: "sb01", name: "Butter Toast", price: 30 },
      { id: "sb02", name: "Masala Toast", price: 40 },
      { id: "sb03", name: "Veg Sandwich", price: 55 },
      { id: "sb04", name: "Club Sandwich", price: 75 },
      { id: "sb05", name: "Garlic Bread", price: 60 },
      { id: "sb06", name: "Bread Pakora (2 pcs)", price: 35 },
      { id: "sb07", name: "Cookies (6 pcs)", price: 50 },
      { id: "sb08", name: "Croissant", price: 45 },
      { id: "sb09", name: "Cheese Sandwich", price: 65 },
      { id: "sb10", name: "Rusk (Packet)", price: 25 },
      { id: "sb11", name: "Muffin (Choco)", price: 55 },
      { id: "sb12", name: "Pav Bhaji", price: 70 },
      { id: "sb13", name: "Paneer Sandwich", price: 80 },
    ],
  },
  {
    id: "sunrise-fast-food",
    name: "Sunrise Fast Food",
    tagline: "Hot, Fast & Delicious",
    emoji: "🍔",
    accent: "#ef4444",
    gradient: "linear-gradient(135deg, #fff5f5 0%, #fee2e2 100%)",
    accentLight: "rgba(239,68,68,0.10)",
    whatsapp: "919876543211",
    category: "Fast Food",
    menu: [
      { id: "sf01", name: "Veg Burger", price: 60 },
      { id: "sf02", name: "Aloo Tikki Burger", price: 55 },
      { id: "sf03", name: "Paneer Burger", price: 80 },
      { id: "sf04", name: "French Fries (Sm)", price: 50 },
      { id: "sf05", name: "French Fries (Lg)", price: 80 },
      { id: "sf06", name: "Veg Pizza (6 inch)", price: 120 },
      { id: "sf07", name: "Cheese Pizza (6 inch)", price: 140 },
      { id: "sf08", name: "Pani Puri (Plate)", price: 30 },
      { id: "sf09", name: "Bhel Puri", price: 35 },
      { id: "sf10", name: "Samosa (2 pcs)", price: 20 },
      { id: "sf11", name: "Veg Roll", price: 65 },
      { id: "sf12", name: "Noodles (Veg)", price: 75 },
      { id: "sf13", name: "Maggi Special", price: 55 },
      { id: "sf14", name: "Corn Chaat", price: 40 },
    ],
  },
  {
    id: "jyoti-juice-corner",
    name: "Jyoti Juice Corner",
    tagline: "Pure, Fresh & Energizing",
    emoji: "🍹",
    accent: "#10b981",
    gradient: "linear-gradient(135deg, #f0fdf4 0%, #d1fae5 100%)",
    accentLight: "rgba(16,185,129,0.10)",
    whatsapp: "919876543212",
    category: "Juices & Drinks",
    menu: [
      { id: "jj01", name: "Fresh Lime Soda", price: 40 },
      { id: "jj02", name: "Mango Shake", price: 70 },
      { id: "jj03", name: "Strawberry Shake", price: 80 },
      { id: "jj04", name: "Banana Shake", price: 60 },
      { id: "jj05", name: "Cold Coffee", price: 65 },
      { id: "jj06", name: "Oreo Shake", price: 85 },
      { id: "jj07", name: "Watermelon Juice", price: 45 },
      { id: "jj08", name: "Mixed Fruit Juice", price: 60 },
      { id: "jj09", name: "Sweet Lassi", price: 45 },
      { id: "jj10", name: "Masala Chaas", price: 30 },
      { id: "jj11", name: "Sugarcane Juice", price: 25 },
      { id: "jj12", name: "Pomegranate Juice", price: 70 },
      { id: "jj13", name: "Virgin Mojito", price: 75 },
    ],
  },
  {
    id: "cake-hut",
    name: "Cake Hut",
    tagline: "Every Bite is a Celebration",
    emoji: "🎂",
    accent: "#8b5cf6",
    gradient: "linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)",
    accentLight: "rgba(139,92,246,0.10)",
    whatsapp: "919876543213",
    category: "Cakes & Desserts",
    menu: [
      { id: "ch01", name: "Chocolate Pastry", price: 60 },
      { id: "ch02", name: "Black Forest Pastry", price: 65 },
      { id: "ch03", name: "Pineapple Pastry", price: 55 },
      { id: "ch04", name: "Red Velvet Slice", price: 75 },
      { id: "ch05", name: "Brownie", price: 50 },
      { id: "ch06", name: "Chocolate Truffle Cake (500g)", price: 350 },
      { id: "ch07", name: "Vanilla Sponge Cake (500g)", price: 280 },
      { id: "ch08", name: "Strawberry Cake (500g)", price: 320 },
      { id: "ch09", name: "Cup Cake (Single)", price: 40 },
      { id: "ch10", name: "Donut (Single)", price: 35 },
      { id: "ch11", name: "Gulab Jamun (4 pcs)", price: 45 },
      { id: "ch12", name: "Rasgulla (4 pcs)", price: 50 },
      { id: "ch13", name: "Chocolate Mousse", price: 90 },
      { id: "ch14", name: "Ice Cream (2 Scoops)", price: 70 },
    ],
  },
];
